# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

variables:
  - group: container-registry

trigger:
  - main

resources:
  - repo: self

stages:
  - stage: Test
    displayName: Test
    jobs:
      - job: sonarqube
        displayName: sonarqube
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: "Docker build & push"
            inputs:
              containerRegistry: $(service_connection_name)
              repository: $(repository_name)
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: '1.0'
